version: '3'

services:
  mysql:
    image: mariadb:10
    environment:
      MYSQL_USER: "username"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "database"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - 3306:3306

  api:
    image: node:10.15-alpine
    working_dir: /app
    environment:
      MARIADB_HOST: "mysql"
    env_file: .env
    command: sh -c "apk add python && npm rebuild && npm run start"
    ports:
      - 3001:3001
    depends_on:
      - mysql
    volumes:
      - ./:/app
