version: '3'

services:
  mysql:
    environment:
      MYSQL_USER: homedb
      MYSQL_PASSWORD: homedb
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: homedb
    volumes:
      - ./database:/var/lib/mysql
      - ./schema:/docker-entrypoint-initdb.d/:ro
    image: mysql:5.7
    ports:
      - 3306:3306

  